CREATE TABLE role (
  id INT PRIMARY KEY AUTO_INCREMENT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NULL,
  update_by INT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  name VARCHAR(50) NOT NULL
) ENGINE=InnoDB;